apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmalert.fullname" . }}
  labels:
    {{- include "vmalert.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vmalert.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vmalert.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vmalert.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8880
              name: web
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - '-rule=/vmalert-conf/*.yaml'
            - '-datasource.url=http://vmselect.default.svc.cluster.local:8481/select/0/prometheus'
            - '-remoteWrite.url=http://vminsert.default.svc.cluster.local:8480/insert/0/prometheus'
            - '-notifier.url=http://alertmanager.default.svc.cluster.local:9093'
          volumeMounts:
            - mountPath: /vmalert-conf
              name: vmalert-volume
      volumes:
        - name: vmalert-volume
          configMap:
            name: vmalert-configuration
